### ISSUE TITLE
Current status / how to get linux running on an OUYA

### ISSUE THREAD

**Issue by cweiske** [pgwipeout/linux#15]
I heard that the linux kernel 5.11 contains the patches that should let it run on an ouya without further modifications:
https://www.phoronix.com/news/Linux-5.11-ARM-Changes

Is there some step-by-step-tutorial how to get a "normal" linux distribution run on the ouya?

I'm not sure if https://github.com/pgwipeout/linux/wiki is still relevant.

**Comment by pgwipeout** [comment]
In all honesty, I haven't done an initial build in years. You'll probably want to build grate-linux https://github.com/grate-driver/linux as it has a number of tegra specific fixes that haven't been mainlined yet.
Steps to get a functional linux build right now:
- Build the kernel, append the dtb to image.gz (may change if you use a different compression algorithm). Make sure you set the command line including `root=`.
- Package image.gz using the android tools and a null initrd (mainline doesn't understand the android dtb and initrd packaging).
- Flash the image as a standard kernel image (remember to use the safeboot stuff for Ouya, or if you bootloop you've soft bricked it).
- Provide an external arm32 rootfs, I use a cheap usb ssd loaded with ubuntu.
- Add the opentegra graphics driver ppa, or build it yourself if not on ubuntu.

I use u-boot chainloaded, but that's some custom stuff and I don't recommend it for new users. It's also possible to replace the bootloader with mainline-ish u-boot using the same compromise as the Switch and some encryption hackery. A tethered bootloader replacement also works and is much easier to pull off.

**Comment by cweiske** [comment]
Thank you!
